version: "3.9"

services:
  backend:
    build: .
    container_name: techmill-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx prisma generate && npm run build && node dist/index.js"
    # ensures Prisma client is generated inside the container before starting

  db:
    image: postgres:15
    container_name: techmill-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techmill
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: